version: '3.7'
services:
  http:
    image: ramageek/php:8.1-javan
    volumes:
      - .:/var/www/html/
    ports:
      - '8080:80'
    environment:
      - SSL_MODE=off
      - AUTORUN_LARAVEL_STORAGE_LINK=false
